cache:
  paths:
    - web/app/themes/casey/node_modules/

build_stage:
  stage: build
  script:
    - date +%Y%m%d%H%M%S > /tmp/STAGE_RELEASE
    - export STAGE_RELEASE=$(cat /tmp/STAGE_RELEASE)
    - echo "Building Stage Release $STAGE_RELEASE"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
  only:
    - stage

deploy_stage:
  stage: deploy
  script:
    - export STAGE_RELEASE=$(cat /tmp/STAGE_RELEASE)
    - echo "Deploying Stage Release $STAGE_RELEASE"
    - mkdir "${STAGE_PATH}releases/${STAGE_RELEASE}"
    - rm -f "${STAGE_PATH}current"
    - ln -s --force "${STAGE_PATH}releases/${STAGE_RELEASE}" "${STAGE_PATH}current"
    - ls -al
  environment:
    name: Staging
    url: https://stage.caseydris.co
  only:
    - stage
