cache:
  paths:
    - web/app/themes/casey/node_modules/

before_script:
  - git clone https://git.caseydris.co/casey/runner-steps.git steps
  - chmod -R 775 steps

build_stage:
  stage: build
  script:
    - export STAGE_RELEASE=$(date +%Y%m%d%H%M%S)
    - steps/build  $STAGE_RELEASE casey
    - steps/deploy $STAGE_PATH $STAGE_RELEASE
    - steps/harden $STAGE_PATH $STAGE_RELEASE
  only:
    - stage

build_prod:
  stage: build
  script:
    - export PROD_RELEASE=$(date +%Y%m%d%H%M%S)
    - steps/build  $PROD_RELEASE casey
    - mkdir -p "${PROD_PATH}releases/${PROD_RELEASE}"
    - touch "${PROD_PATH}current"
    - rm -f "${PROD_PATH}current"
    - ln -s "${PROD_PATH}releases/${PROD_RELEASE}" "${PROD_PATH}current"
    - rsync -r ./config "${PROD_PATH}current"
    - rsync -r ./vendor "${PROD_PATH}current"
    - rsync -r --exclude-from=".rsync" ./web "${PROD_PATH}current"
    - mkdir -p "${PROD_PATH}shared/web/app"
    - rm -rf "${PROD_PATH}releases/${PROD_RELEASE}/web/app/uploads"
    - ln -s "${PROD_PATH}shared/web/app/uploads" "${PROD_PATH}releases/${PROD_RELEASE}/web/app/uploads"
    - ln -s "${PROD_PATH}shared/.env" "${PROD_PATH}releases/${PROD_RELEASE}/.env"
    - chown -R :www-data "${PROD_PATH}current"
    - chown -R :www-data "${PROD_PATH}releases/${PROD_RELEASE}"
    - find "${PROD_PATH}releases/${PROD_RELEASE}" -type d -exec chmod 755 {} \;
    - find "${PROD_PATH}releases/${PROD_RELEASE}" -type f -exec chmod 644 {} \;
  only:
    - prod
