cache:
  paths:
    - web/app/themes/casey/node_modules/

build_stage:
  script:
    - echo "Building Staging"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
    - cd ../../../../
    - export STAGE_RELEASE=$(date +%Y%m%d%H%M%S)
    - echo $STAGE_RELEASE
    - mkdir /srv/www/caseydris.co/stage_html/releases/$STAGE_RELEASE
  stage: build
  only:
    - stage

deploy_stage:
  script:
    - echo "Deploying Staging"
  environment:
    name: Staging
    url: https://stage.caseydris.co
  only:
    - stage
