cache:
  paths:
    - web/app/themes/casey/node_modules/

before_script:
  - git clone https://git.caseydris.co/casey/runner-steps.git steps
  - chmod -R 775 steps

build_stage:
  stage: build
  script:
    - export STAGE_RELEASE=$(date +%Y%m%d%H%M%S)
    - composer remove johnpbloch/wordpress
    - composer clear-cache
    - composer require johnpbloch/wordpress:4.7.3
    - steps/build  $STAGE_RELEASE casey
    - steps/deploy $STAGE_PATH $STAGE_RELEASE
    - steps/harden $STAGE_PATH $STAGE_RELEASE
  only:
    - stage

build_prod:
  stage: build
  script:
    - export PROD_RELEASE=$(date +%Y%m%d%H%M%S)
    - steps/build  $PROD_RELEASE casey
    - steps/deploy $PROD_PATH $PROD_RELEASE
    - steps/harden $PROD_PATH $PROD_RELEASE
  only:
    - prod
