cache:
  paths:
    - web/app/themes/casey/node_modules/

build_stage:
  stage: build
  script:
    - export STAGE_RELEASE=$(date +%Y%m%d%H%M%S)
    - echo "Building Stage Release $STAGE_RELEASE"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
    - mkdir "${STAGE_PATH}releases/${STAGE_RELEASE}"
    - rm -f "${STAGE_PATH}current"
    - ln -s "${STAGE_PATH}releases/${STAGE_RELEASE}" "${STAGE_PATH}current"
    - cd ../../../..
    - rsync -r ./config "${STAGE_PATH}current"
    - rsync -r ./vendor "${STAGE_PATH}current"
    - rsync -r --exclude-from=".rsync" ./web "${STAGE_PATH}current"
    - ln -s "${STAGE_PATH}shared/web/app/uploads" "${STAGE_PATH}releases/${STAGE_RELEASE}/web/app/uploads"
    - ln -s "${STAGE_PATH}shared/.env" "${STAGE_PATH}releases/${STAGE_RELEASE}/.env"
    - chown -R :www-data "${STAGE_PATH}current"
  only:
    - stage

build_prod:
  stage: build
  script:
    - export PROD_RELEASE=$(date +%Y%m%d%H%M%S)
    - echo "Building Prod Release PROD_RELEASE"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
    - mkdir -p "${PROD_PATH}releases/${PROD_RELEASE}"
    - touch "${PROD_PATH}current"
    - rm -f "${PROD_PATH}current"
    - ln -s "${PROD_PATH}releases/${PROD_RELEASE}" "${PROD_PATH}current"
    - cd ../../../..
    - rsync -r ./config "${PROD_PATH}current"
    - rsync -r ./vendor "${PROD_PATH}current"
    - rsync -r --exclude-from=".rsync" ./web "${PROD_PATH}current"
    - mkdir -p "${PROD_PATH}shared/web/app"
    - ln -s "${PROD_PATH}shared/web/app/uploads" "${PROD_PATH}releases/${PROD_RELEASE}/web/app/uploads"
    - ln -s "${PROD_PATH}shared/.env" "${PROD_PATH}releases/${PROD_RELEASE}/.env"
    - chown -R :www-data "${PROD_PATH}current"
  only:
    - prod
