cache:
  paths:
  - web/app/themes/casey/node_modules/

stage:
  script:
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
  only:
    - stage
