cache:
  paths:
    - web/app/themes/casey/node_modules/

before_script:
  - date +%Y%m%d%H%M%S > STAGE_RELEASE

build_stage:
  stage: build
  script:
    - export STAGE_RELEASE=$(cat STAGE_RELEASE)
    - echo "Building Stage Release $STAGE_RELEASE"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
  only:
    - stage

deploy_stage:
  stage: deploy
  script:
    - export STAGE_RELEASE=$(cat STAGE_RELEASE)
    - echo "Deploying Stage Release $STAGE_RELEASE"
    - mkdir "${STAGE_PATH}releases/${STAGE_RELEASE}"
    - ln -s "${STAGE_PATH}releases/${STAGE_RELEASE}" "${STAGE_PATH}current"
    - ll -al
    - chown -R :www-data $STAGE_PATH
  environment:
    name: Staging
    url: https://stage.caseydris.co
  only:
    - stage
