cache:
  paths:
    - web/app/themes/casey/node_modules/

variables:
  STAGE_RELEASE: $(date +%Y%m%d%H%M%S)

build_stage:
  stage: build
  script:
    - echo "Building Stage Release $STAGE_RELEASE"
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
  only:
    - stage

deploy_stage:
  stage: deploy
  script:
    - echo "Deploying Stage Release $STAGE_RELEASE"
    - mkdir $STAGE_PATH$STAGE_RELEASE
  environment:
    name: Staging
    url: https://stage.caseydris.co
  only:
    - stage
