cache:
  paths:
    - web/app/themes/casey/node_modules/

build_stage:
  script:
    - bundle install
    - composer install
    - cd web/app/themes/casey
    - composer install
    - npm install
    - yarn run build:production
    - cd ../../../../
    - cap staging deploy --trace
  stage: build
  only:
    - stage
