cache:
  paths:
    - web/app/themes/casey/node_modules/

before_script:
  - git clone https://git.caseydris.co/casey/runner-steps.git steps
  - chmod -R 775 steps
  - export CI_RELEASE=$(date +%Y%m%d%H%M%S)

build_stage:
  stage: build
  script:
    - steps/build  $CI_RELEASE casey
    - steps/deploy $STAGE_PATH $CI_RELEASE
    - steps/harden $STAGE_PATH $CI_RELEASE
    - steps/backup $STAGE_PATH $CI_RELEASE
  only:
    - stage

build_prod:
  stage: build
  script:
    - steps/build  $CI_RELEASE casey
    - steps/deploy $PROD_PATH $CI_RELEASE
    - steps/harden $PROD_PATH $CI_RELEASE
    - steps/backup $PROD_PATH $CI_RELEASE
  only:
    - prod
